Test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -285,6 +285,13 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ github.token }}
+      - name: Setup ccache
+        uses: actions/cache@v5
+        with:
+          path: .ccache
+          key: ccache-ffmpeg-${{ matrix.target }}-${{ matrix.variant }}-${{ github.sha }}
+          restore-keys: |
+            ccache-ffmpeg-${{ matrix.target }}-${{ matrix.variant }}-
       - name: Build ffmpeg
         run: |
           T="$(echo -n ${{ github.token }} | sha256sum | head -c 64)" && echo -e "::add-mask::${T}\n::stop-commands::${T}"
@@ -340,8 +347,18 @@ jobs:
           NAME="Latest Auto-Build (${{ steps.create_release.outputs.rel_date }})"
           TAGNAME="latest"
           gh release delete --cleanup-tag --yes "$TAGNAME" || true
-          sleep 15
-          gh release create "$TAGNAME" --target "master" --title "$NAME" latest_artifacts/*
+          success=false
+          for i in {1..30}; do
+            if gh release create "$TAGNAME" --target "master" --title "$NAME" latest_artifacts/*; then
+              success=true
+              break
+            fi
+            sleep 2
+          done
+          if [ "$success" = false ]; then
+            echo "Failed to create release after 30 attempts."
+            exit 1
+          fi
         env:
           GITHUB_TOKEN: ${{ github.token }}
       - name: Update Wiki
